# Basic App Info
spring.application.name=feefo
server.port=3000

# Database Configuration (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Health Check (Actuator) Configuration
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health

# Ensure smooth routing between Controllers and Actuator
spring.mvc.pathmatch.matching-strategy=ant_path_matcher